version: '3.4'

services:
  db:
    image: mysql:8.0.19
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:    
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: rest_with_asp_net_udemy
    ports:
      - "3306:3306"
    volumes:
      - type: bind
        source: ./DBBackup/backup.sql
        target: /docker-entrypoint-initdb.d/backup.sql
    networks:
      - udemy-network

  restwithaspnetudemy:
    image: restwithaspnetudemy-api
    build:
      context: .
      dockerfile: RestWithASPNETUdemy/Dockerfile
    environment:    
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "5000:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network

networks: 
    udemy-network:
        driver: bridge